/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ProcessorTest {
    @Test public void testSomeLibraryMethod() {
        Processor processor = new Processor();
        assertTrue(processor.process("hello world").matches("11:\\d*"));
    }
}
