/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.hamcrest.Matchers.matchesPattern;
import static org.junit.Assert.*;

public class ProcessorTest {
    @Test public void testSomeLibraryMethod() {
        Processor processor = new Processor();
        assertThat(processor.process("hello world"), matchesPattern("\\d*:11"));
    }
}
